name: Push WordPress Plugin to SVN
on:
  push:
    tags:
    - "*"
jobs:
  tag:
    name: New tag
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install PHP
      uses: shivammathur/setup-php@v2 # https://github.com/marketplace/actions/setup-php-action
      with:
        php-version: '5.6'
        extensions: iconv, intl, mysqli, oauth
        ini-values: error_reporting=-1, memory_limit=512M, post_max_size=256M, xdebug.mode="coverage,debug,develop"
        coverage: xdebug #optional
    - name: Check Versions
      run: |
        php -v
        php -r 'echo "curl version: " . curl_version()["version"] . "\n";'
        composer --version
    - name: Validate composer.json and composer.lock
      run: composer validate --strict
    - name: Cache composer packages
      uses: actions/cache@v4
      id: composer-cache
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: |
        composer install --no-dev --prefer-dist --no-progress
    - name: Move plugin file
      run: |
        php dev/buildWordPressPlugin.php
    - name: WordPress Plugin Deploy
      uses: 10up/action-wordpress-plugin-deploy@stable
      env:
        SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
        SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
        SLUG: phpdebugconsole
